### ISSUE TITLE
Return Mismatch on Repeated Logins

### ISSUE THREAD

**Issue by brholtkamp** [RoboticCheese/mac-app-store-chef#41]
Hey there,

I've been tinkering around with a provisioning cookbook and noticed that it fails when using Chef as a service running as root (probably related to #39).  It appears that when using rtun with a system user, it will set it properly for that designated user.  However, when you run a cookbook/recipe again that calls it, it will return 7 instead of the 6 that is currently expected:

```
brian-mbp% mas signout
brian-mbp% mas signin blah@gmail.com 'password'
==> Signing in to Apple ID: blah@gmail.com
brian-mbp% echo $?
0
brian-mbp% mas signin blah@gmail.com 'password'
brian-mbp% echo $?
7
```

We could fix this by changing [`L201`](https://github.com/RoboticCheese/mac-app-store-chef/blob/master/libraries/resource_mac_app_store_mas.rb#L201), though I'm unaware of if you have more planned with #39, so that's why I'm sending this as an issue instead of a PR.

Have you ran into this / can recreate what I'm running into?

Thanks for the awesome cookbook!

**Comment by RoboticCheese** [comment]
Between the latest versions of Mas and the cookbook, I think this is fixed...(?) Mas now works when run as root, so I ripped out all the "run as a regular user" workarounds for the 3.0.0 release. It should also be smarter about not trying to sign in multiple times and failing.

At least, I've been running it as root on my laptop for the last couple weeks and haven't had anymore of the old failure conditions that I'd seen.
